$base = "D:\train\Training\Training"
$newBase = "D:\train\Training\Training"

# Helper function to create dir and copy file
function CopyTo($src, $destDir, $newName) {
    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    Copy-Item $src "$destDir\$newName" -Force
}

# 01 - Calculator
CopyTo "$base\Task 1\index.html"    "$newBase\01_calculator" "calculator.html"
CopyTo "$base\Task 1\index.js"      "$newBase\01_calculator" "calculator.js"
CopyTo "$base\Task 1\style.css"     "$newBase\01_calculator" "calculator.css"
$c = Get-Content "$newBase\01_calculator\calculator.html" -Raw
$c = $c -replace 'href="style\.css"','href="calculator.css"' -replace 'src="index\.js"','src="calculator.js"'
Set-Content "$newBase\01_calculator\calculator.html" $c -NoNewline

# 02 - Number Guessing Game
CopyTo "$base\Task 2\game.html"     "$newBase\02_number_guessing_game" "game.html"
CopyTo "$base\Task 2\game.js"       "$newBase\02_number_guessing_game" "game.js"
CopyTo "$base\Task 2\game.css"      "$newBase\02_number_guessing_game" "game.css"

# 03 - Word Sorter
CopyTo "$base\Task 3\index.html"    "$newBase\03_word_sorter" "word-sorter.html"
CopyTo "$base\Task 3\task3.js"      "$newBase\03_word_sorter" "word-sorter.js"
$c = Get-Content "$newBase\03_word_sorter\word-sorter.html" -Raw
$c = $c -replace 'src="task3\.js"','src="word-sorter.js"'
Set-Content "$newBase\03_word_sorter\word-sorter.html" $c -NoNewline

# 04 - Array Filtering
CopyTo "$base\Task 4\tas4.html"     "$newBase\04_array_filtering" "array-filter.html"

# 05 - Birthday Calendar
CopyTo "$base\Task 5\task5.html"    "$newBase\05_birthday_calendar" "birthday-calendar.html"
CopyTo "$base\Task 5\task5.js"      "$newBase\05_birthday_calendar" "birthday-calendar.js"
$c = Get-Content "$newBase\05_birthday_calendar\birthday-calendar.html" -Raw
$c = $c -replace 'src="task5\.js"','src="birthday-calendar.js"'
Set-Content "$newBase\05_birthday_calendar\birthday-calendar.html" $c -NoNewline

# 06 - Dynamic Table
CopyTo "$base\Task 6\Task6.html"    "$newBase\06_dynamic_table" "dynamic-table.html"

# 07 - DOM Manipulation
CopyTo "$base\Task 7\task7.html"    "$newBase\07_dom_manipulation" "dom-manipulation.html"
CopyTo "$base\Task 7\MS_Static.png" "$newBase\07_dom_manipulation" "MS_Static.png"

# 08 - DOM Playground
CopyTo "$base\Task 8\task8.html"    "$newBase\08_dom_playground" "dom-playground.html"

# 09 - Array Rendering
CopyTo "$base\Task9\task9.html"     "$newBase\09_array_rendering" "array-rendering.html"

# 10 - Mean & Median Calculator
CopyTo "$base\Task10\task10.html"   "$newBase\10_mean_median_calculator" "mean-median.html"

# 11 - Array Max/Min
CopyTo "$base\Task11\task11.html"   "$newBase\11_array_max_min" "array-max-min.html"

# 12 - Student Performance
CopyTo "$base\Task12\task12.html"   "$newBase\12_student_performance" "student-performance.html"

# 13 - Student Form
CopyTo "$base\Task13\task13.html"   "$newBase\13_student_form" "student-form.html"

# Concepts
CopyTo "$base\Testing 1\test1.html" "$newBase\concepts\01_var_let_const"        "var-let-const.html"
CopyTo "$base\Testing 1\test2.html" "$newBase\concepts\02_functions_callbacks"  "functions-callbacks.html"
CopyTo "$base\Testing 1\test3.html" "$newBase\concepts\03_call_stack"           "call-stack.html"

Write-Host "✅ Reorganization complete!" -ForegroundColor Green

# ─── Generate data.js ───────────────────────────────────────────────────────
$explorerDir = "D:\train\Training\explorer"
New-Item -ItemType Directory -Path $explorerDir -Force | Out-Null

function ReadCode($path) {
    if (Test-Path $path) {
        return (Get-Content $path -Raw) | ConvertTo-Json
    }
    return '""'
}

$trainingRel = "../Training"

$js = @"
// Auto-generated by reorganize.ps1
const PROJECTS = [
  {
    id: "01_calculator",
    title: "Calculator",
    description: "Interactive calculator with +, -, *, / operations using DOM events and eval()",
    topics: ["DOM", "Events", "Functions"],
    difficulty: "Beginner",
    folder: "01_calculator",
    previewFile: "calculator.html",
    files: [
      { name: "calculator.html", lang: "html",       content: $(ReadCode "$newBase\01_calculator\calculator.html") },
      { name: "calculator.js",   lang: "javascript",  content: $(ReadCode "$newBase\01_calculator\calculator.js") },
      { name: "calculator.css",  lang: "css",          content: $(ReadCode "$newBase\01_calculator\calculator.css") }
    ]
  },
  {
    id: "02_number_guessing_game",
    title: "Number Guessing Game",
    description: "Guess a number 1-10 with 5 attempts. Prize money decreases with each wrong guess",
    topics: ["DOM", "Events", "Game Logic", "Math.random"],
    difficulty: "Beginner",
    folder: "02_number_guessing_game",
    previewFile: "game.html",
    files: [
      { name: "game.html", lang: "html",       content: $(ReadCode "$newBase\02_number_guessing_game\game.html") },
      { name: "game.js",   lang: "javascript",  content: $(ReadCode "$newBase\02_number_guessing_game\game.js") },
      { name: "game.css",  lang: "css",          content: $(ReadCode "$newBase\02_number_guessing_game\game.css") }
    ]
  },
  {
    id: "03_word_sorter",
    title: "Word Sorter",
    description: "Sort words in a sentence alphabetically using split(), sort() and join()",
    topics: ["Arrays", "String Methods", "DOM"],
    difficulty: "Beginner",
    folder: "03_word_sorter",
    previewFile: "word-sorter.html",
    files: [
      { name: "word-sorter.html", lang: "html",       content: $(ReadCode "$newBase\03_word_sorter\word-sorter.html") },
      { name: "word-sorter.js",   lang: "javascript",  content: $(ReadCode "$newBase\03_word_sorter\word-sorter.js") }
    ]
  },
  {
    id: "04_array_filtering",
    title: "Array Filtering by Property",
    description: "Filter an array of person objects to display only Telugu speakers using a for loop",
    topics: ["Arrays", "Objects", "Loops", "Conditionals"],
    difficulty: "Beginner",
    folder: "04_array_filtering",
    previewFile: "array-filter.html",
    files: [
      { name: "array-filter.html", lang: "html", content: $(ReadCode "$newBase\04_array_filtering\array-filter.html") }
    ]
  },
  {
    id: "05_birthday_calendar",
    title: "Birthday Calendar",
    description: "Birthday calendar that shows personalized messages based on today's date using Date API and find()",
    topics: ["Date API", "Arrays", "DOM", "find()"],
    difficulty: "Intermediate",
    folder: "05_birthday_calendar",
    previewFile: "birthday-calendar.html",
    files: [
      { name: "birthday-calendar.html", lang: "html",       content: $(ReadCode "$newBase\05_birthday_calendar\birthday-calendar.html") },
      { name: "birthday-calendar.js",   lang: "javascript",  content: $(ReadCode "$newBase\05_birthday_calendar\birthday-calendar.js") }
    ]
  },
  {
    id: "06_dynamic_table",
    title: "Dynamic Table Generator",
    description: "Generate an HTML table dynamically from an array of objects using DOM createElement",
    topics: ["DOM Manipulation", "Arrays", "Objects", "Bootstrap"],
    difficulty: "Intermediate",
    folder: "06_dynamic_table",
    previewFile: "dynamic-table.html",
    files: [
      { name: "dynamic-table.html", lang: "html", content: $(ReadCode "$newBase\06_dynamic_table\dynamic-table.html") }
    ]
  },
  {
    id: "07_dom_manipulation",
    title: "DOM Manipulation",
    description: "Change title style, dynamically add paragraphs, and remove an image element from the DOM",
    topics: ["DOM Manipulation", "Events", "createElement", "removeElement"],
    difficulty: "Beginner",
    folder: "07_dom_manipulation",
    previewFile: "dom-manipulation.html",
    files: [
      { name: "dom-manipulation.html", lang: "html", content: $(ReadCode "$newBase\07_dom_manipulation\dom-manipulation.html") }
    ]
  },
  {
    id: "08_dom_playground",
    title: "DOM Playground",
    description: "Live text styling tool — change color, font size, background, then export display as PNG via html2canvas",
    topics: ["DOM", "Events", "Canvas API", "html2canvas"],
    difficulty: "Intermediate",
    folder: "08_dom_playground",
    previewFile: "dom-playground.html",
    files: [
      { name: "dom-playground.html", lang: "html", content: $(ReadCode "$newBase\08_dom_playground\dom-playground.html") }
    ]
  },
  {
    id: "09_array_rendering",
    title: "Array Rendering to DOM",
    description: "Render a supercars array as a dynamic unordered list using map() and innerHTML",
    topics: ["Arrays", "DOM", "Template Literals", "map()"],
    difficulty: "Beginner",
    folder: "09_array_rendering",
    previewFile: "array-rendering.html",
    files: [
      { name: "array-rendering.html", lang: "html", content: $(ReadCode "$newBase\09_array_rendering\array-rendering.html") }
    ]
  },
  {
    id: "10_mean_median_calculator",
    title: "Mean & Median Calculator",
    description: "Enter 5 numbers sequentially and calculate their mean and median using reduce() and sort()",
    topics: ["Arrays", "Math", "reduce()", "sort()", "Statistics"],
    difficulty: "Intermediate",
    folder: "10_mean_median_calculator",
    previewFile: "mean-median.html",
    files: [
      { name: "mean-median.html", lang: "html", content: $(ReadCode "$newBase\10_mean_median_calculator\mean-median.html") }
    ]
  },
  {
    id: "11_array_max_min",
    title: "Array Max / Min (Age Finder)",
    description: "Find the oldest and youngest person from an array of objects using Math.max, Math.min, spread operator and find()",
    topics: ["Arrays", "Math.max", "Math.min", "find()", "Spread Operator"],
    difficulty: "Beginner",
    folder: "11_array_max_min",
    previewFile: "array-max-min.html",
    files: [
      { name: "array-max-min.html", lang: "html", content: $(ReadCode "$newBase\11_array_max_min\array-max-min.html") }
    ]
  },
  {
    id: "12_student_performance",
    title: "Student Performance Report",
    description: "Calculate averages using reduce(), classify students with filter(), and render a performance table with DOM",
    topics: ["Arrays", "map()", "filter()", "reduce()", "DOM"],
    difficulty: "Intermediate",
    folder: "12_student_performance",
    previewFile: "student-performance.html",
    files: [
      { name: "student-performance.html", lang: "html", content: $(ReadCode "$newBase\12_student_performance\student-performance.html") }
    ]
  },
  {
    id: "13_student_form",
    title: "Student Info Form → JSON",
    description: "Student information form with checkboxes that collects data and outputs it as formatted JSON with clipboard copy",
    topics: ["Forms", "DOM", "JSON", "Events", "Checkboxes"],
    difficulty: "Intermediate",
    folder: "13_student_form",
    previewFile: "student-form.html",
    files: [
      { name: "student-form.html", lang: "html", content: $(ReadCode "$newBase\13_student_form\student-form.html") }
    ]
  }
];

const CONCEPTS = [
  {
    id: "concept_var_let_const",
    title: "var vs let vs const",
    description: "7 comprehensive tests covering scope, hoisting, redeclaration, TDZ and global object differences",
    topics: ["var", "let", "const", "Scope", "Hoisting", "TDZ"],
    difficulty: "Intermediate",
    folder: "concepts/01_var_let_const",
    previewFile: "var-let-const.html",
    files: [
      { name: "var-let-const.html", lang: "html", content: $(ReadCode "$newBase\concepts\01_var_let_const\var-let-const.html") }
    ]
  },
  {
    id: "concept_functions_callbacks",
    title: "Functions & Callbacks",
    description: "Sandbox with commented examples of regular functions, arrow functions, callbacks, setTimeout and Map",
    topics: ["Functions", "Arrow Functions", "Callbacks", "Map", "setTimeout"],
    difficulty: "Beginner",
    folder: "concepts/02_functions_callbacks",
    previewFile: "functions-callbacks.html",
    files: [
      { name: "functions-callbacks.html", lang: "html", content: $(ReadCode "$newBase\concepts\02_functions_callbacks\functions-callbacks.html") }
    ]
  },
  {
    id: "concept_call_stack",
    title: "Call Stack Demo",
    description: "Visual demonstration of JavaScript call stack and nested function execution order",
    topics: ["Call Stack", "Function Execution", "Execution Context"],
    difficulty: "Beginner",
    folder: "concepts/03_call_stack",
    previewFile: "call-stack.html",
    files: [
      { name: "call-stack.html", lang: "html", content: $(ReadCode "$newBase\concepts\03_call_stack\call-stack.html") }
    ]
  }
];
"@

Set-Content "$explorerDir\data.js" $js -Encoding UTF8
Write-Host "✅ data.js generated!" -ForegroundColor Green
